import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv("../venv/.env")

def generate_report(clean_schema: dict, rag_context: str = "") -> str:
    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise RuntimeError("GROQ_API_KEY not found in environment variables")

    client = Groq(api_key=api_key)

    prompt = f"""
You are an AI assistant responsible for generating an official Sunday Service Report
for CHAPEL OF PEACE AND JOY, LEAD CITY UNIVERSITY.

Your task is to generate a clear, formal, and well-structured report using ONLY
the information provided. This report will be submitted as an official church document.

--------------------
STRICT RULES
--------------------
1. Follow the report template EXACTLY in structure and section order.
2. Do NOT invent, assume, or add any information that is not provided.
3. If a section has no data, omit that section completely.
4. Maintain a formal, reverent, church-report tone.
5. Use clear paragraphs and bullet points where appropriate.
6. Do NOT mention that this report was generated by AI.

--------------------
REPORT TEMPLATE
--------------------

CHAPEL OF PEACE AND JOY  
LEAD CITY UNIVERSITY  

Sunday Service Report

Heading  
Service Date: {{service_date}}  
Service Theme: {{service_theme}}  
Start Time: {{start_time}}  
Venue: {{venue}}  

Section A – Workers’ Charge Programme Outline  
- Opening Time  
- Opening Prayer & Worship  
- Sessions & Facilitators  
- Key Highlights  

Section B – Service Outline  
- Order of Service  

Section C – Sermon Highlights  
- Sermon Topic  
- Preacher  
- Scripture(s)  
- Main Thought  
- Key Points  

Section D – Attendance  
Male: {{male}}  
Female: {{female}}  
Total: {{total}}  

Section E – Challenges Encountered  

Section F – Session Authorship  
Report Prepared By  
Role / Unit  
Date of Submission  

--------------------
SERVICE DATA (JSON)
--------------------
{{SERVICE_DATA}}

--------------------
OPTIONAL STYLE CONTEXT (PAST REPORT EXCERPTS)
--------------------
{{RAG_CONTEXT}}

--------------------
OUTPUT INSTRUCTIONS
--------------------
Generate the complete Sunday Service Report as a single, well-formatted document.
Do not include placeholders, brackets, or explanations.

""".replace("{{SERVICE_DATA}}", json.dumps(clean_schema, indent=2)) \
   .replace("{{RAG_CONTEXT}}", rag_context or "None")

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2
    )

    return response.choices[0].message.content
